app/cathai/views.py
import requests
from app import csrf, app

from flask import Blueprint, Response, request
from flask_login import login_required

cathai = Blueprint('cathai', __name__)

def process_request(path, request, PROXY_URL):
    headers = {}
    headers['Cookie'] = dict(request.headers)['Cookie']
    headers['Referer'] = PROXY_URL
    query = request.query_string.decode("utf-8")
    if len(query) > 0:
        if '?' in path:
            path = path + "&" + query
        else:
            path = path + "?" + query
    if request.method =='GET':
        resp = requests.get(path, headers=headers)
    elif request.method =='POST':
        resp = requests.post(path, headers=headers, data=dict(request.form))
    excluded_headers = ['content-encoding', 'content-length', 'transfer-encoding', 'connection']
    headers = [(name, value) for (name, value) in  resp.raw.headers.items() if name.lower() not in excluded_headers]
    response = Response(resp.content, resp.status_code, headers)
    return response


@cathai.route('/demo/',methods=['GET','POST'])
@csrf.exempt
def demo_base():
    PROXY_URL = 'http://127.0.0.1:3840/'
    path = f'{PROXY_URL}'
    return process_request(path, request, PROXY_URL)

@cathai.route('/demo/<path:path>',methods=['GET','POST'])
@csrf.exempt
def demo_files(path):
    PROXY_URL = 'http://127.0.0.1:3840/'
    path = f'{PROXY_URL}{path}'
    return process_request(path, request, PROXY_URL)

if app.config['STAND_ALONE'] == False:
    @cathai.route('/',methods=['GET','POST'])
    @csrf.exempt
    @login_required
    def index():
        PROXY_URL = 'http://127.0.0.1:3838/'
        path = f'{PROXY_URL}'
        return process_request(path, request, PROXY_URL)

    @cathai.route('/<path:path>',methods=['GET','POST'])
    @csrf.exempt
    @login_required
    def cathai_files(path):
        PROXY_URL = 'http://127.0.0.1:3838/'
        path = f'{PROXY_URL}{path}'
        return process_request(path, request, PROXY_URL)
else:
    @cathai.route('/',methods=['GET','POST'])
    @csrf.exempt
    def index():
        PROXY_URL = 'http://127.0.0.1:3838/'
        path = f'{PROXY_URL}'
        return process_request(path, request, PROXY_URL)

    @cathai.route('/<path:path>',methods=['GET','POST'])
    @csrf.exempt
    def cathai_files(path):
        PROXY_URL = 'http://127.0.0.1:3838/'
        path = f'{PROXY_URL}{path}'
        return process_request(path, request, PROXY_URL)

app/main/__init__.py
from app.main import errors  # noqa
from app.main.views import main, clust # noqa

app/main/views.py
from flask import Blueprint, render_template
from app import app
import app.cluster as cluster

main = Blueprint('main', __name__)
clust = Blueprint('admin', __name__)

if app.config['STAND_ALONE'] == False:
    from app.models import EditableHTML
    @main.route('/')
    def index():
        # editable_html_obj = EditableHTML.get_editable_html('home')
        # return render_template('main/index.html', editable_html_obj=editable_html_obj)
        return render_template('main/index.html')


    @main.route('/about')
    def about():
        # editable_html_obj = EditableHTML.get_editable_html('about')
        # return render_template('main/about.html', editable_html_obj=editable_html_obj)
        return render_template('main/about.html')

else:
    @main.route('/')
    def index():
        return render_template('main/index.html', editable_html_obj="", standalone=True)


    @main.route('/about')
    def about():
        return render_template('main/about.html', editable_html_obj="")


    @clust.route('/clusters')
    def manage_clusters():
        return cluster.manage_clusters()


    @clust.route('/cluster/<cluster_id>')
    @clust.route('/cluster/<cluster_id>/info')
    def cluster_info(cluster_id):
        return cluster.cluster_info(cluster_id)


    @clust.route('/cluster/<cluster_id>/edit', methods=['GET', 'POST'])
    def edit_cluster(cluster_id):
        return cluster.edit_cluster(cluster_id)


    @clust.route('/cluster/<cluster_id>/delete')
    def delete_cluster_request(cluster_id):
        return cluster.delete_cluster_request(cluster_id)


    @clust.route('/cluster/<cluster_id>/_delete')
    def delete_cluster(cluster_id):
        return cluster.delete_cluster(cluster_id)


    @clust.route('/new-cluster', methods=['GET', 'POST'])
    def new_cluster():
        return cluster.new_cluster()


    @clust.route('/get_sts')
    def get_sts():
        return cluster.get_sts()


    @clust.route('/get_members')
    def get_members():
        return cluster.get_members()

    @clust.route('/get_distances')
    def get_distances():
        return cluster.get_distances()


    @clust.route('/get_metadata')
    def get_metadata():
        return cluster.get_metadata()

app/templates/main/about.html
{% import 'macros/page_macros.html' as page %}
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui text container">
        <h1>About</h1>
        {{ page.render_inline_editor(editable_html_obj, current_user, stand_alone) }}
    </div>

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

app/templates/main/index copy.html
<!DOCTYPE html>
<html>
    <head>
        {% include 'partials/_head.html' %}
    </head>
    <body>
        {% include 'partials/_flashes.html' %}

        <div class="ui header headfloat"><h1><em>CATHAI</em></h1>
          <div class="sub header"><h3>Cluster Analysis Tool for Healthcare-Associated Infections</h3></div>
        </div>
        <hr class="solid">
        <div class="ui grid">
            <div class="three wide column mainfloat">
                <div class="two wide centered column">
                    <p><h2><a class="black" href="#"><em>Download</em></a></h2></p>
                    <p><h2><a class="black" href="{{ url_for('cathai.demo_base') }}"><em>Demo</em></a></h2></p>
                    <p><h2><a class="black" href="{{ url_for('account.login') }}"><em>Login</em></a></h2></p>
                </div>
            </div>
            <div class="thirteen wide column">
                <img class="ui image mainimg" src="{{ url_for('static', filename='images/cathai_bg.png') }}">
            </div>
        </div>
        <hr class="solid">

        {% if csrf_token()|safe %}
            <div style="visibility: hidden; display: none">
              <input type="hidden" name="csrf_token" value="{{ csrf_token()|safe }}">
            </div>
        {% endif %}
    </body>
</html>

app/templates/main/index.html
<!DOCTYPE html>
<html>
    <head>
        {% include 'partials/_head.html' %}
    </head>
    <body>
        {% include 'partials/_flashes.html' %}

        <div class="ui header headfloat"><h1><em>CATHAI</em></h1>
          <div class="sub header"><h3>Cluster Analysis Tool for Healthcare-Associated Infections</h3></div>
        </div>
        <hr class="solid">
        <div class="ui grid maingrid">
            <div class="sixteen wide column mainfloat">
                {% if standalone is defined %}
                    <p><h2><a class="black" href="{{ url_for('cathai.index') }}"><em>Access CATHAI</em></a></h2></p>
                    <p><h2><a class="black" href="{{ url_for('admin.manage_clusters') }}"><em>Manage Clusters</em></a></h2></p>
                    <p><h2><a class="black" href="{{ url_for('admin.new_cluster') }}"><em>Add New Cluster</em></a></h2></p>
                {% else %}
                    {% if current_user.is_authenticated %}
                    <p><h2><a class="black" href="{{ url_for('cathai.index') }}"><em>Access CATHAI</em></a></h2></p>
                    <p><h2><a class="black" href="{{ url_for(current_user.role.index + '.index') }}"><em>Access Dashboard</em></a></h2></p>
                    {% else %}
                    <p><h2><a class="black" href="{{ url_for('account.login') }}"><em>Login</em></a></h2></p>
                    <p><h2><a class="black" href="{{ url_for('cathai.demo_base') }}"><em>Demo</em></a></h2></p>
                    {% endif %}
                    <p><h2><a class="black" target="_blank" href="https://github.com/FordeGenomics/CATHAI"><em>Download</em></a></h2></p>
                {% endif %}
                
            </div>
        </div>
        <hr class="solid">

        {% if csrf_token()|safe %}
            <div style="visibility: hidden; display: none">
              <input type="hidden" name="csrf_token" value="{{ csrf_token()|safe }}">
            </div>
        {% endif %}
        <footer>
        </footer>
    </body>
</html>

app/templates/main/index_orig.html
{% import 'macros/page_macros.html' as page %}
{% extends 'layouts/base.html' %}


{% block content %}
    <div class="ui text container">
      <h1>CATHAI 3.0</h1>
      {{ page.render_inline_editor(editable_html_obj, current_user, stand_alone) }}
    </div>

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}